
n = int(input("Enter the number of integers you'd like to enter: "))
print()
list_numbers = list()
for i in range(n):
   x = int(input("Enter the integer: "))
   list_numbers.append(x)
   print()
print()
nl = tuple(list_numbers)
print(nl, "Is my tuple.")
print()
print(max(nl), "is the HIGHEST value in the tuple.")
print()
print(min(nl), "is the LOWEST value in the tuple.")
print()
print(sum(nl), "is the SUM of the values in the tuple.")
print()
s = sum(nl)
l = len(nl)
